"""add learned_models table

Revision ID: d50d33f0d7ec
Revises: 79db34545ba6
Create Date: 2026-06-19 11:43:35.729791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50d33f0d7ec'
down_revision: Union[str, Sequence[str], None] = '79db34545ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('coef', sa.String(), nullable=True),
    sa.Column('mean', sa.String(), nullable=True),
    sa.Column('std', sa.String(), nullable=True),
    sa.Column('intercept', sa.Float(), nullable=True),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learned_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learned_models_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learned_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learned_models_active'))

    op.drop_table('learned_models')
    # ### end Alembic commands ###
